JR = java
JCC = javac
JFLAGS = -g

default: switchCF.class codingExercise12.class codingExercise13.class codingExercise14.class codingExercise15.class codingExercise16.class codingExercise17.class codingExercise18.class codingExercise19.class codingExercise20.class codingExercise21.class codingExercise22.class codingExercise23.class codingExercise24.class codingExercise25.class codingExercise26.class codingExercise27.class codingExercise28.class forLoop.class


switchCF.class: switchCF.java
	$(JCC) $(JFLAGS) switchCF.java
	$(JR) switchCF
codingExercise12.class: codingExercise12.java
	$(JCC) $(JFLAGS) codingExercise12.java
	$(JR) codingExercise12
codingExercise13.class: codingExercise13.java
	$(JCC) $(JFLAGS) codingExercise13.java
	$(JR) codingExercise13
codingExercise14.class: codingExercise14.java
	$(JCC) $(JFLAGS) codingExercise14.java
	$(JR) codingExercise14
codingExercise15.class: codingExercise15.java
	$(JCC) $(JFLAGS) codingExercise15.java
	$(JR) codingExercise15
codingExercise16.class: codingExercise16.java
	$(JCC) $(JFLAGS) codingExercise16.java
	$(JR) codingExercise16
codingExercise17.class: codingExercise17.java
	$(JCC) $(JFLAGS) codingExercise17.java
	$(JR) codingExercise17
codingExercise18.class: codingExercise18.java
	$(JCC) $(JFLAGS) codingExercise18.java
	$(JR) codingExercise18
codingExercise19.class: codingExercise19.java
	$(JCC) $(JFLAGS) codingExercise19.java
	$(JR) codingExercise19
codingExercise20.class: codingExercise20.java
	$(JCC) $(JFLAGS) codingExercise20.java
	$(JR) codingExercise20
codingExercise21.class: codingExercise21.java
	$(JCC) $(JFLAGS) codingExercise21.java
	$(JR) codingExercise21
codingExercise22.class: codingExercise22.java
	$(JCC) $(JFLAGS) codingExercise22.java
	$(JR) codingExercise22
codingExercise23.class: codingExercise23.java
	$(JCC) $(JFLAGS) codingExercise23.java
	$(JR) codingExercise23
codingExercise24.class: codingExercise24.java
	$(JCC) $(JFLAGS) codingExercise24.java
	$(JR) codingExercise24
codingExercise25.class: codingExercise25.java
	$(JCC) $(JFLAGS) codingExercise25.java
	$(JR) codingExercise25
codingExercise26.class: codingExercise26.java
	$(JCC) $(JFLAGS) codingExercise26.java
	$(JR) codingExercise26
codingExercise27.class: codingExercise27.java
	$(JCC) $(JFLAGS) codingExercise27.java
	$(JR) codingExercise27
codingExercise28.class: codingExercise28.java
	$(JCC) $(JFLAGS) codingExercise28.java
	$(JR) codingExercise28
forLoop.class: forLoop.java
	$(JCC) $(JFLAGS) forLoop.java
	$(JR) forLoop
clean:
	$(RM) *.class
