JR = time java
JCC = javac
JFLAGS = -g

default: oopClass.class #codingExercise29.class codingExercise30.class codingExercise31.class codingExercise32.class codingExercise33.class codingExercise34.class codingExercise35.class codingExercise36.class

oopClass.class: oopClass.java
	$(JCC) $(JFLAGS) oopClass.java
	$(JR) oopClass
#codingExercise29.class: codingExercise29.java
#	$(JCC) $(JFLAGS) codingExercise29.java
#	$(JR) codingExercise29
#codingExercise30.class: codingExercise30.java
#	$(JCC) $(JFLAGS) codingExercise30.java
#	$(JR) codingExercise30
#codingExercise31.class: codingExercise31.java
#	$(JCC) $(JFLAGS) codingExercise31.java
#	$(JR) codingExercise31
#codingExercise32.class: codingExercise32.java
#	$(JCC) $(JFLAGS) codingExercise32.java
#	$(JR) codingExercise32
#codingExercise33.class: codingExercise33.java
#	$(JCC) $(JFLAGS) codingExercise33.java
#	$(JR) codingExercise33
#codingExercise34.class: codingExercise34.java
#	$(JCC) $(JFLAGS) codingExercise34.java
#	$(JR) codingExercise34
#codingExercise35.class: codingExercise35.java
#	$(JCC) $(JFLAGS) codingExercise35.java
#	$(JR) codingExercise35
#codingExercise36.class: codingExercise36.java
#	$(JCC) $(JFLAGS) codingExercise36.java
#	$(JR) codingExercise36


clean:
	$(RM) *.class
